### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by JoergSH** [neandr/piScheduler#1]
Hello,
just installed pi Schedule and get it work now.
I just have some question:

Is it normal that i have to start it as root like "sudo python piSchedule.py newDaySchedule.ini"?

How to start automatic after boot the pi?

Must be restart piSchedule after changing the ini?

thanks a lot in advance

Joerg

**Comment by neandr** [comment]
Hello Joerg    
thanks for posting, see comments below 
>Is it normal that i have to start it as root like "sudo python piSchedule.py newDaySchedule.ini"?

It should work also without sudo.   
Please check the rights. I have:
<code>-rwxr-xr-x 1 pi   pi   20490 Mar 15 13:28 piSchedule.py</code>


>How to start automatic after boot the pi?

Another *piSchedule* user (framp) proposed this:
><code> /etc/fstab:
    @reboot        root    ( sleep 15; /usr/local/bin/startScheduler.sh)</code>

For @reboot he also wrote:    
> Das ist ein Feature was nicht gross bekannt ist: Hier sind eine Menge crontab Beispiele - u.A. dann auch der reboot Parameter
http://www.thegeekstuff.com/2009/06/15-practical-crontab-examples/

With .ini file usage :    

>Must be restart piSchedule after changing the ini?             

At the moment with piConsole you can pass commands or an .ini file. That will __add__ that command(s) to the actual schedule list for the actual day. The problem is you may end up with more than one set of schedule jobs. This will be changed for the next version.    
So, yes at the moment it may be recommaned to restart *piSchedule* for another .ini file.

**Comment by framps** [comment]
I use following command to stop piScheduler and start it with a different .ini file. That way I can have different .ini files used on different days. I just have to setup a cron job which stops piScheduler some mins after midnight and start it with a different .ini file. 

kill -2 $(ps -ef | grep "python.*piScheduler" | grep -v grep | awk '{ print $2; }')
